### ISSUE TITLE
Potential issue with some math

### ISSUE THREAD

**Issue by slayorktc** [unl1k3ly/AnchorHODL#13]
I came across your repo which I found very cool but decided to turn it into a telegram bot only for status of loans. I noticed how you were calculating some of the math and there might be an issue you overlooked. 

`query_msg_anchor_deposited = {
        "balance": {
            "address": account_address,
        },
    }
    total_deposited_amount = terra.wasm.contract_query(aTerra, query_msg_anchor_deposited)
`

This returns the balance of "aUST" (the amount of tokens) which is not the USD/UST price/value. In the beginning they were most likely very close to 1:1 but now this produces different value. I am not sure if you were aware of this. Currently aUST is valued at 1:1.1 (see on dashboard page) I added this code below to calculate the deposited in UST value.

`    query_msg_a_exchange_rate = {
        "epoch_state": {
        },
    }
    a_exchange_rate = terra.wasm.contract_query(mmMarket, query_msg_a_exchange_rate)`

  `  total_deposited_amount = (float(total_deposited_amount['balance']) / 1000000 * float(a_exchange_rate['exchange_rate']))
`

If your code is operating correctly then close this out. Wanted to bring this up just in case it could become an issue in the future.

**Comment by unl1k3ly** [comment]
fixed in the current released
