### ISSUE TITLE
Query for loan_amount is not the outstanding loan, interest missing

### ISSUE THREAD

**Issue by realkibou** [unl1k3ly/AnchorHODL#15]
There is a bug in the query from Terra. If you query for
```
query_msg_loan = {
        "borrower_info": {
            "borrower": account_address
        },
    }
```
you will get the loan_amount from the initial borrowing. This does NOT incl. the interest, hence the LTV is calculated "too save" / loo low. To fix this just query for **any** block_height.

```
query_msg_loan = {
        "borrower_info": {
            "borrower": account_address,
            "block_height": 1
        },
    }
```

**Comment by unl1k3ly** [comment]
you are correct, I'll implement this one on next release for bombay. Thanks for bringing this up

**Comment by unl1k3ly** [comment]
https://github.com/unl1k3ly/AnchorHODL/blob/dev/anchorprotocol.py#L164

**Comment by fentas** [comment]
Hey, sorry to pick this up again but maybe help me out.
I try to get the loan amount for a specific block height. Is that possible as block_height seems arbitrary?

In the end, I want to figure out the occurred interest.
