### ISSUE TITLE
loan repay amounts may leave UST below 0.25 threshold for repay.

### ISSUE THREAD

**Issue by conradjohnson** [unl1k3ly/AnchorHODL#2]
Requesting a static buffer in wallet when repaying loans in order to ensure continuation of payments and not get frozen with zero balance in wallet, but still deposits in anchor to repay loan.

Current behavior: if wallet is below threshold to repay, withdrawals from anchor deposit and repays loan.  A last transaction in a series of transactions might leave the wallet below the 0.25 threshold for the next transaction.  

Requested behavior: if wallet is below threshold to repay, withdrawals from anchor deposit to repay loan and ensure a buffer of UST in wallet for future (possibly burst rapid) transactions.  $1.51 should be enough buffer for 6 rapid  txs and it's funny because: liquor.

**Comment by unl1k3ly** [comment]
Hi mate, 

App will withdraw from Earn, if not enough sitting in the wallet. That amount will also include fees from treasury + gas.

When paying from the wallet I'm considering a flat amount of $10 to cover for fees. You can change/check this line at:
- https://github.com/unl1k3ly/AnchorHODL/blob/main/anchor_loan_repay.py#L243

Cheers

**Comment by conradjohnson** [comment]
Ah.  Wallet balance I was testing had under $10 to begin with remainder in
anchor.  Repay amounts of 6.32 and 3.45

I'll set wallet to have $11 and see if I can reproduce again.
