### ISSUE TITLE
Note on the Readme

### ISSUE THREAD

**Issue by Philipp-Sc** [unl1k3ly/AnchorHODL#23]
- The command shown in the download.gif is outdated
- Consider changing the Docker run command to `docker run -d -p 127.0.0.1:5000:5000 anchorhodl:latest`

Docker opens the port to the world if `127.0.0.1:` is not added as prefix. (Additionally it would be great to protect the webpage by a password, so than not everybody can access it)

Best regards,
Philipp-Sc

**Comment by unl1k3ly** [comment]
Done it ! https://github.com/unl1k3ly/AnchorHODL/commit/e784c0f39ef9c53b2c2db5158449d9e1affac0df
