### ISSUE TITLE
ERROR keep_loan_safe

### ISSUE THREAD

**Issue by yoikoh** [unl1k3ly/AnchorHODL#26]
Hi, sorry newbie here.
Keep getting this error. Any idea how to resolve this?

![image](https://user-images.githubusercontent.com/92195240/136642481-29ba3204-4e79-43fd-b6a1-b3cc626c4bf1.png)

tried _git reset --hard & git pull_ then _pip3 install --upgrade --force-reinstall -r requirements.txt_ but got the following instead

![image](https://user-images.githubusercontent.com/92195240/136642688-c4afa8a3-f464-414a-9e80-13ecd7d79581.png)

**Comment by estalldecker** [comment]
This is the same issue as this one right? https://github.com/unl1k3ly/AnchorHODL/issues/20. You should be able to solve it ;)
