### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by JezzaT** [unl1k3ly/AnchorHODL#3]
Hi, 
I'm running the docker version and i get the following error when running it.
![image](https://user-images.githubusercontent.com/85694355/121551789-48f45300-ca53-11eb-85e0-73581f80df48.png)

**Comment by unl1k3ly** [comment]
Simplify because you have no borrow amount to be paid or nothing deposit in
anchor earn.

Cheers

**Comment by JezzaT** [comment]
Hi,

I have Borrow funds deposited into Earn and still have the same error.
Would this be the same error if the seed phrase was incorrect?

**Comment by unl1k3ly** [comment]
correct. If the seed is not right, then I'm sure there's no funds...

For testing, you can use testnet.

Cheers

**Comment by JezzaT** [comment]
HI, Sorry to be a pest.
I've tried this with 2 different seeds, on 3 different dockers (Mac, Linux, Windows) in 2 different physical locations & still get the same issue. I'm thinking it must be something stupid that i'm doing wrong.
In config.py i've replaced ('MNEMONIC', 'paste your seed here') with ('MNEMONIC', '_my seed phrase_') and left everyting else the same.
I've compiled the container with no errors, and run it with no errors.
I've Borrowed $5 and put it in Earn & i have over 10 UST in my wallet.
![image](https://user-images.githubusercontent.com/85694355/121792589-70594480-cc3a-11eb-8204-7f16766d168d.png)

On the Inspect tab in Docker all the variables are listed and filled out except MNEMONIC, which is blank. I assume this is a  security thing? Or is it possible that the seed isn't getting added when the container is compiled?
I'm out of ideas, any light you can shed on this would be greatly appreciated.

**Comment by unl1k3ly** [comment]
Hi,

Could you please try without the docker ? Simply feed config.py, install requirements py `pip3 install -r requirements.txt`  and run `python3 web_view.py.py` Let me know if any issues..

It seems your seed is not going to the env variables, hence bot is not working for you.

DM me on TG when you online, i can help you out.

Cheers

**Comment by unl1k3ly** [comment]
Hi Jezza,

Did you sort this out ?

I've looked at the code and I'm assuming a loan is something greater than
10 UST ... I guess this would be your problem no ?

Cheers
