### ISSUE TITLE
Repay transaction cost

### ISSUE THREAD

**Issue by MeCrazyJunkie** [unl1k3ly/AnchorHODL#5]
Hi.
Auto repay transaction fee is 5 times higher than manual repay. Why?

Auto repay transaction: https://finder.terra.money/columbus-4/tx/E5FE126057AE6CF4973E7C19481B29E8C80AF0A948E5C6C9C0AEBB6A46F59C2C

Manual repay transaction (I've made it with same sum for proof): https://finder.terra.money/columbus-4/tx/BCA3C18CDEABFCADCA95AD52478DB9B2D2371D5454363270EAD9CB54583F645E

**Comment by unl1k3ly** [comment]
Hi mate, 

Indeed I'm using the tax_cap to avoid network congestion when paying. That was what saved me from being liquidated when network were congentioned when everyone were trying to pay off loan at the same time.

I'm assuming the repay won't trigger as much hence I can cope with higher fees here.

In fact, it can be changed later on...

Cheers
