### ISSUE TITLE
Where can I find the terra addresses in contact_address.py? 

### ISSUE THREAD

**Issue by pablovela5620** [unl1k3ly/AnchorHODL#7]
I've been looking, but don't have too much experience and haven't been able to find them online

**Comment by unl1k3ly** [comment]
What ? Really don't know what you saying... Could you please be more
specific?

**Comment by pablovela5620** [comment]
Sorry about that, should have probably been more clear. I was basically looking for this https://docs.anchorprotocol.com/smart-contracts/deployed-contracts but I ended up finding it! Appreciate you open sourcing this, already using it, and its working great 🚀

**Comment by unl1k3ly** [comment]
No worries! Don't forget to donate!!!
