### ISSUE TITLE
Question about Columbus-5

### ISSUE THREAD

**Issue by Philipp-Sc** [unl1k3ly/AnchorHODL#9]
Hi there,

thank you for creating AnchorHODL.

I would like to know if the script needs to be updated once Columbus-5 is implemented.
I ask this just to make sure, that the script continues to work correctly, since a pause could be fatal.

Thank you for all your work & best regards,
Philipp

**Comment by unl1k3ly** [comment]
Hi mate, sure thing ! I'll make sure it works at testnet and by the time col-5 is at mainnet this script will be fully working as its current state! Don't need to worry on that, I do personally relay on this code too !! :) Cheers
